# Site settings
title: "Resume :: S.H.Cheon"
description: "Resume :: S.H.Cheon"

# Build settings
markdown: kramdown
sass:
  sass_dir: _sass
  style: compressed

# Resume settings
resume_avatar:                  "false"
resume_name:                    "Resume (천승현)"
resume_title:                   "Introduce"

# used for the contact button in _layouts/resume.html
resume_contact_email:           "tlakdl00@naver.com"

# the next two items are used for schema itemprops in _layouts/resume.html
resume_contact_telephone:       "010-8693-9678"
resume_contact_address:         "경기도 안양시"

resume_header_contact_info:     ""
display_header_contact_info:    "false"

resume_header_intro: "<p> 안녕하세요.<br>
Embedded S/W 개발부터 시작하여 여러 산업 분야에 대한 IT 서비스 개발/운영을 수행한 풍부한 경험을 가지고 있습니다.
항상 배우고자 하는 자세로 어떠한 도메인 분야에 대한 IT 업무를 담당하여도, 빠르게 적응하여 성과를 창출해왔습니다.
업무가 주어지면 책임감을 가지고 맡은 역할을 완수하고자 노력하며, 매번 한 단계 성장하는 것을 즐기는 개발자입니다.
</p>"



# use "yes" to display the email contact button,
# "no" to display an "I'm not looking for work" message,
# or remove the resume_looking_for_work option entirely
# to leave blank
resume_looking_for_work:        "false"

# Decide which sections to use
# comment out to hide
resume_section_experience:      true
resume_section_education:       true
resume_section_projects:        true
resume_section_recognition:     true
resume_section_links:           false
resume_section_skills:          false
resume_section_associations:    false
resume_section_interests:       false

# Resume social links
# uncomment the options you wish to display, and add your own URL
resume_social_links:
  # resume_github_url:            "https://github.com/jglovier/resume-template"
  # resume_twitter_url:           "http://twitter.com/jglovier"
  # resume_dribbble_url:          "https://dribbble.com/jag"
  # resume_facebook_url:          "insert Facebook URL here"
  # resume_linkedin_url:          "https://www.linkedin.com/in/joelglovier"
  # resume_instagram_url:         "insert your Instagram URL here"
  # resume_website_url:           "http://joelglovier.com"
  # resume_medium_url:            "https://medium.com/@jglovier"
# resume_print_social_links:      true

# Design settings
resume_theme:                   default

# Note: when editing locally, remember to restart
# your Jekyll server when you edit this file. Changes
# to _config.yml are only recognized when the server starts
